version: '3.7'
services:
  backend:
    container_name: backend_dev
    depends_on: 
      - db
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
    command: npm run start:dev
    env_file:
        - .env

  db:
    container_name: mongol
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
